variable "repository_name" {}
variable "repository_description" {}
variable "visibility" {}
variable "template_owner" {}
variable "template_repository" {}
variable "aws_access_key" {}
variable "aws_secret_key" {}
variable "aws_region" {}
variable "aws_s3_bucket_name" {}